name: electromagnetic-risk-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - requests
  - matplotlib
  - scikit-learn
  - jupyter
  - ipykernel
  - seaborn
  - statsmodels
  - pip
  - pip:
    # Add any pip-only packages here if needed
